# Support this project
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: nirbhays
# ko_fi: your_username   # Uncomment and add if you set up Ko-fi
# patreon: your_username # Uncomment and add if you set up Patreon
